---
title: "Alpha_Diversity"
output: html_document
---

```{r}
#Loading the packages needed for Alpha diversity measures and statistical 
#analysis. 



library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)
library(picante)
library(ape)
library(dunn.test)
library(ggsignif)
```


```{r}
#Importing processed phyloseq object from generate_phyloseq.Rmd

ps <- readRDS('../processed_data/phyloseq_taxonomy.rds')

```

```{r}
psrare= ps %>% rarefy_even_depth(sample.size = 5396, rngseed = 360)

#The rarefraction depth was decided based on qiime 2 outputs 
```
Shannon's Diversity Index

HA and NA
```{r}
set.seed(360)
p = plot_richness(psrare, x="HA_NA",
                        measures = c("Shannon"),
                  color= "HA_NA")

pdata = p$data


# p_formatted = pdata %>% ggplot(aes(HA_NA,value, fill = HA_NA)) +
#   geom_boxplot(outlier.shape = NA, alpha = 0.6) +
#   geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
# theme_classic(base_size=16)+
#   ylab("Shannon Diversity") + xlab(NULL) +
#   theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
#   labs(fill= "HA_NA")
# p_formatted
```

```{r}

#Statistical significance 
df <- data.frame(HA_NA = as.factor(pdata$HA_NA), value = pdata$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig <-dunn.test(df$value, df$HA_NA, kw=TRUE, method = "bh")

results_df <- data.frame(
  subtype_comparison = res_sig$comparisons,
  p_adjusted = res_sig$P.adjusted
)


```

```{r}
set.seed(360)
p_NA_shannon = plot_richness(psrare, x="na_subtype",
                        measures = c("Shannon"),
                  color= "na_subtype")

pdata_NA_shannon = p_NA_shannon$data

# p_formatted_NA = pdata_NA_shannon %>% ggplot(aes(na_subtype,value, fill = na_subtype)) +
#   geom_boxplot(outlier.shape = NA, alpha = 0.6) +
#   geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
# theme_classic(base_size=16)+
#   ylab("Shannon Diversity") + xlab(NULL) +
#   theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
#   labs(fill= "na_subtype")
# p_formatted_NA


```

```{r}
df_NA_shannon <- data.frame(na_subtype = as.factor(pdata_NA_shannon$na_subtype), value = pdata_NA_shannon$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig_NA <-dunn.test(df_NA_shannon$value, df_NA_shannon$na_subtype, kw=TRUE,
                    method = "bh")

results_df_NA <- data.frame(
  subtype_comparison = res_sig_NA$comparisons,
  p_adjusted = res_sig_NA$P.adjusted
)


```

```{r}
set.seed(360)
p_HA_shannon = plot_richness(psrare, x="ha_subtype",
                        measures = c("Shannon"),
                  color= "ha_subtype")

pdata_HA_shannon = p_HA_shannon$data

```

```{r}
df_HA_shannon <- data.frame(ha_subtype = as.factor(pdata_HA_shannon$ha_subtype), value = pdata_HA_shannon$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig_HA <-dunn.test(df_HA_shannon$value, df_HA_shannon$ha_subtype, kw=TRUE,
                    method = "bh")

results_df_HA <- data.frame(
  subtype_comparison = res_sig_HA$comparisons,
  p_adjusted = res_sig_HA$P.adjusted
)

```
NA_subtype Aggregated 
```{r}
set.seed(360)
p_NA_aggr_shannon = plot_richness(psrare, x="na_aggr",
                        measures = c("Shannon"),
                  color= "na_aggr")

pdata_NA_aggr_shannon = p_NA_aggr_shannon$data

p_formatted_NA_aggr = pdata_NA_aggr_shannon %>% ggplot(aes(na_aggr,value, fill = na_aggr)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
theme_classic(base_size=16)+
  ylab("Shannon Diversity") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
  labs(fill= "na_aggr")
p_formatted_NA_aggr

```

```{r}
df_NA_aggr_shannon <- data.frame(na_aggr = as.factor(pdata_NA_aggr_shannon$na_aggr), value = pdata_NA_aggr_shannon$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig_aggr_NA <-dunn.test(df_NA_aggr_shannon$value, df_NA_aggr_shannon$na_aggr, kw=TRUE, method = "bh")



#one significant group
```
HA_subtype Aggregrated 
```{r}
set.seed(360)
p_HA_aggr_shannon = plot_richness(psrare, x="ha_aggr",
                        measures = c("Shannon"),
                  color= "ha_aggr")

pdata_HA_aggr_shannon = p_HA_aggr_shannon$data

p_formatted_HA_aggr = pdata_HA_aggr_shannon %>% ggplot(aes(ha_aggr,value, fill = ha_aggr)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
theme_classic(base_size=16)+
  ylab("Shannon Diversity") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
  labs(fill= "ha_aggr")
p_formatted_HA_aggr

```

```{r}
df_HA_aggr_shannon <- data.frame(ha_aggr = as.factor(pdata_HA_aggr_shannon$ha_aggr), value = pdata_HA_aggr_shannon$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig_aggr_HA <-dunn.test(df_HA_aggr_shannon$value, df_HA_aggr_shannon$ha_aggr, kw=TRUE, method = "bh")

#one significant group

```
HA Phylogenetic Groups
```{r}
set.seed(360)
p_HA_group_shannon = plot_richness(psrare, x="ha_group",
                        measures = c("Shannon"),
                  color= "ha_group")

pdata_HA_group_shannon = p_HA_group_shannon$data

p_formatted_HA_group = pdata_HA_group_shannon %>% ggplot(aes(ha_group,value, 
                                                             fill = ha_group)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
theme_classic(base_size=16)+
  ylab("Shannon Diversity") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
  labs(fill= "HA Phylogenetic Groups")
p_formatted_HA_group

```

```{r}
df_HA_group_shannon <- data.frame(ha_group = as.factor(pdata_HA_group_shannon$ha_group), value = pdata_HA_group_shannon$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig_group_HA <-dunn.test(df_HA_group_shannon$value, df_HA_group_shannon$ha_group, kw=TRUE, method = "bh")

view(res_sig_group_HA)

#Two significant groups

```

```{r}

P_signif_group_HA <- p_formatted_HA_group + geom_signif(
    comparison = list(c("1", "neg"), c("2","neg")),
    y_position = c(4.5,4),
    annotations = c("*","*")
  )
P_signif_group_HA
```
NA Phylogenetic Groups
```{r}
set.seed(360)
p_NA_group_shannon = plot_richness(psrare, x="na_group",
                        measures = c("Shannon"),
                  color= "na_group")

pdata_NA_group_shannon = p_NA_group_shannon$data

p_formatted_NA_group = pdata_NA_group_shannon %>% ggplot(aes(na_group,value, 
                                                             fill = na_group)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
theme_classic(base_size=16)+
  ylab("Shannon Diversity") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
  labs(fill= "NA Phylogenetic Groups")
p_formatted_NA_group

```
```{r}
df_NA_group_shannon <- data.frame(na_group = as.factor(pdata_NA_group_shannon$na_group), value = pdata_NA_group_shannon$value)
#Kruskal-Wallis and Dunn's test as post-hoc
res_sig_group_NA <-dunn.test(df_NA_group_shannon$value, df_NA_group_shannon$na_group, kw=TRUE, method = "bh")

view(res_sig_group_NA)
```
```{r}
P_signif_group_NA <- p_formatted_NA_group + geom_signif(
    comparison = list( c("2","neg")),
    y_position = c(4),
    annotations = c("*")
  )
P_signif_group_NA
```



Faith's Diversity

```{r}
# Setup ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# taxa must be columns instead of rows, this will convert it if needed
otu = as(otu_table(psrare), "matrix")
if(taxa_are_rows(psrare)==TRUE) otu <- t(otu)

# Extract your phyloseq object's tree
tree_faith = phy_tree(psrare)

# check that all the ASV names match between OTU table and tree
stopifnot(all(colnames(otu) %in% tree_faith$tip.label))
# reorder tree tips to match ASV order, if needed:
# Won't hurt to run this on your data if it's unnecessary.
#    remove any unmatched tips
tree_faith = drop.tip(tree_faith, setdiff(tree_faith$tip.label, colnames(otu)))
#    reorder to match
tree_faith = keep.tip(tree_faith, colnames(otu))

# root the tree if it's unrooted
if(!is.rooted(tree_faith)) tree_faith <- root(tree_faith, outgroup=tree_faith$tip.label[1], resolve.root=TRUE)

# Calculate Faith's PD for each sample ~~~~~~~~~~~~
#    1. Convert reads to presence/absence and pull into a matrix
otu_pa = otu # Make a copy of your data, then...
otu_pa[otu_pa>0] = 1 #...convert to presence/absence (1 for present, 0 for absent)
#    2. Calculate metric
faith = pd(otu_pa, tree_faith, include.root = TRUE) %>% select(-SR)

view(pdata)


# Now you can add this to your phyloseq data and plot it like the other metrics!

metadata_rarefied = data.frame(sample_data(psrare))

faith_metadata = merge(metadata_rarefied, faith, by= "row.names")

view(faith_metadata)




```
HA_NA
```{r}
faith_HA_NA_df <- data.frame(HA_NA = as.factor(faith_metadata$HA_NA), value = faith_metadata$PD)

faith_HA_NA_sig <-dunn.test(faith_HA_NA_df$value, faith_HA_NA_df$HA_NA, kw=TRUE, method = "bh")
```
NA Subtype
```{r}
faith_NA_df <- data.frame(na_subtype = as.factor(faith_metadata$na_subtype), 
                                                 value = faith_metadata$PD)
faith_NA_sig <- dunn.test(faith_NA_df$value, faith_NA_df$na_subtype, kw=TRUE, method = "bh")
```
HA Subtype
```{r}
faith_HA_df <- data.frame(ha_subtype = as.factor(faith_metadata$ha_subtype), 
                                                 value = faith_metadata$PD)
faith_HA_sig <- dunn.test(faith_HA_df$value, faith_HA_df$ha_subtype, kw=TRUE, method = "bh")
```
NA Subtype Aggregated 
 
```{r}
faith_NA_aggr_df <- data.frame(na_aggr = as.factor(faith_metadata$na_aggr), 
                                                 value = faith_metadata$PD)
faith_NA_aggr_sig <- dunn.test(faith_NA_aggr_df$value, faith_NA_aggr_df$na_aggr, kw=TRUE, method = "bh")

#Kruskal Wallis of 0.05 but no observed significant pairs
```
HA Subtype Aggregated 
 
```{r}
faith_HA_aggr_df <- data.frame(ha_aggr = as.factor(faith_metadata$ha_aggr), 
                                                 value = faith_metadata$PD)
faith_HA_aggr_sig <- dunn.test(faith_HA_aggr_df$value, faith_HA_aggr_df$ha_aggr, kw=TRUE, method = "bh")

#one significant group
```
 
HA Phylogenetic Groups

```{r}
faith_formatted_HA_group = faith_metadata %>% ggplot(aes(ha_group,PD, 
                                                             fill = ha_group)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
theme_classic(base_size=16)+
  ylab("Faith's Diversity") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
  labs(fill= "HA Phylogenetic Groups")
faith_formatted_HA_group
```


```{r}
faith_HA_group_df <- data.frame(ha_group = as.factor(faith_metadata$ha_group), 
                                                 value = faith_metadata$PD)
faith_HA_group_sig <- dunn.test(faith_HA_group_df$value, faith_HA_group_df$ha_group, kw=TRUE, method = "bh")

view(faith_HA_group_sig)
```
```{r}
P_faith_group_HA <- faith_formatted_HA_group + geom_signif(
    comparison = list(c("1", "neg"), c("2","neg")),
    y_position = c(13.5,13),
    annotations = c("**","*")
  )
P_faith_group_HA
```

NA Phylogenetic Group
```{r}
faith_formatted_NA_group = faith_metadata %>% ggplot(aes(na_group,PD, 
                                                             fill = na_group)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(height= 0, width = 0.20, size = 1.5, alpha= 0.4) +
theme_classic(base_size=16)+
  ylab("Faith's Diversity") + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1, size=12)) +
  labs(fill= "NA Phylogenetic Groups")
faith_formatted_NA_group
```



```{r}
faith_NA_group_df <- data.frame(na_group = as.factor(faith_metadata$na_group), 
                                                 value = faith_metadata$PD)
faith_NA_group_sig <- dunn.test(faith_NA_group_df$value, faith_NA_group_df$na_group, kw=TRUE, method = "bh")
```
```{r}
P_faith_group_NA <- faith_formatted_NA_group + geom_signif(
    comparison = list(c("1", "neg"), c("2","neg")),
    y_position = c(13.5,13),
    annotations = c("*","**")
  )
P_faith_group_NA
```

 
 



